### ISSUE TITLE
Document height employee show

### ISSUE THREAD

**Issue by budi7** [ThunderID/HRIS-V.2#1]
![screen shot 2016-04-11 at 5 01 43 pm](https://cloud.githubusercontent.com/assets/10555410/14423687/41ad7516-0007-11e6-82c0-5ca804cea05d.png)

**Comment by chelsymooy** [comment]
Fixed https://github.com/ThunderID/HRIS-V.2/commit/356b0fd805a439de80ed0914a6c27fc457fd681b
